services:
  node-react:
    container_name: next_template_1_prod
    image: node:lts-alpine  # Using the official node image directly
    environment:
      - COMPOSE_BAKE=true
    working_dir: /app
    ports:
      - '1112:3000'
    volumes:
      - .:/app  # Mount the entire project directory
    command: sh -c "npm install && npm start"  # Ensure dependencies are installed
    networks:
      - ecom_1_next_prod__network

networks:
  ecom_1_next_prod__network:
    driver: bridge
